### ISSUE TITLE
Upload file to action

### ISSUE THREAD

**Issue by ikudeljnj** [Rhetos/Rhetos#164]
Hi!

I have a use case where i need to upload Excel files and import them to table. We've been thinking about writing a concept which would have a rest code generator, but since each import is heavily dependant on various data, conclusion was that each upload will need specific code. 

The idea was to have an action which accepts byte64 or byte[]. We've tried using 
Parameter 
{
  Binary File;
}

but get a problem with deserializing:
2019-07-03 10:17:01.0454|ERROR|GlobalErrorHandler|System.Runtime.Serialization.SerializationException: There was an error deserializing the object of type MasterData.ImportCommodities. End element 'file' from namespace '' expected. Found text 'data:application/vnd.openxmlformats-officedocument.spreadsheetml.sheet;base64,

Can you give us some guidelines in terms of what would be the best course of action from your perspective?

We're using Angular on front end, for reference

**Comment by bantolov** [comment]
Have you considered using [Rhetos.LightDMS](https://github.com/Rhetos/LightDMS/) plugin? It provides **more efficient web methods for uploading and downloading files** with streaming.

I am not sure what caused the error above. Uploading binaries without LightDMS, directly through standard Rhetos REST API should also work, even if not very efficient.
For example:

```c
Module Demo
{
    Entity FileStorage
    {
        ShortString Name;
        Binary Content;
    }

    // This action is not needed.
    // It is be better to simply insert into FileStorage.
    Action SaveFile
        '(parameter, repository, userInfo) =>
        {
            repository.Demo.FileStorage.Insert(
                new Demo.FileStorage
                {
                    Name = parameter.Name,
                    Content = parameter.Content
                });
        }'
    {
        ShortString Name;
        Binary Content;
    }
}
```

Direct insert into FileStorage:

```
Request:
  POST: http://localhost/Rhetos/rest/Demo/FileStorage/
  Content-Type: application/json; charset=utf-8
  Body: { "Name":"readme.txt", "Content":[65,66,67] }
Response:
  200 OK
  { "ID": "1bedd715-cc38-4ab6-981d-65b0855847b9" }
```

Executing action:

```
Request:
  POST: http://localhost/Rhetos/rest/Demo/SaveFile/
  Content-Type: application/json; charset=utf-8
  Body: { "Name":"readme2.txt", "Content":[65,66,67,68] }
Response:
  200 OK
```
